[package]
name = "postgresql"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { version = "0.1.0", path = "../../domain" }

[dependencies.lazy_static]
version = "1.5.0"

[dependencies.diesel]
version = "2.2.6"
features = ["postgres", "chrono", "uuid", "r2d2"]

[dependencies.uuid]
version = "1.11.1"
features = ["v4"]

[dependencies.dotenvy]
version = "0.15.7"